// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class PersonsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryID");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryID = new Guid("d8c07225-bc6a-4b15-b520-a1f7131f46f6"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryID = new Guid("01ef672f-5aef-4c0c-8474-babf107220fd"),
                            CountryName = "UK"
                        },
                        new
                        {
                            CountryID = new Guid("920f3264-4d96-4245-9f2f-7ff14d766887"),
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryID = new Guid("a2053bf3-7aaa-4c77-a23d-8fbbea341754"),
                            CountryName = "Russia"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.Property<string>("TIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("ABC12345")
                        .HasColumnName("TaxIdentificationNumber");

                    b.HasKey("PersonID");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonID = new Guid("a7ab253e-05c7-4bf7-93aa-22e551124171"),
                            Address = "address1",
                            CountryID = new Guid("920f3264-4d96-4245-9f2f-7ff14d766887"),
                            DateOfBirth = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johndoe1@gmail.com",
                            Gender = "Female",
                            PersonName = "John Doe1",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("ed9623aa-e92c-4170-8c76-f0660d783f05"),
                            Address = "address2",
                            CountryID = new Guid("d8c07225-bc6a-4b15-b520-a1f7131f46f6"),
                            DateOfBirth = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johndoe2@gmail.com",
                            Gender = "Other",
                            PersonName = "John Doe2",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("9219bbdd-d30c-45f4-929f-024d9904f188"),
                            Address = "address3",
                            CountryID = new Guid("01ef672f-5aef-4c0c-8474-babf107220fd"),
                            DateOfBirth = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johndoe3@gmail.com",
                            Gender = "Female",
                            PersonName = "John Doe3",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonID = new Guid("fdb0ae15-1d53-460d-9352-75a67293c731"),
                            Address = "address4",
                            CountryID = new Guid("a2053bf3-7aaa-4c77-a23d-8fbbea341754"),
                            DateOfBirth = new DateTime(1999, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "johndoe4@gmail.com",
                            Gender = "Male",
                            PersonName = "John Doe4",
                            ReceiveNewsLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
